/* DO NOT EDIT THIS FILE */
//this is an example of inheritance between classes

//include required libraries
#include <iostream>
#include <string>

//include time so we can calculate the current year later
#include <ctime>

//use all names in standard library
using namespace std;

//declaring the parent class
class Person {
  //parent attributes - keeping these public for now for simplicity sake
  public:
    string fname;
    string lname;
    string email;
    string status;

  //parent methods here

}; //end parent class definition

//defining a student class that is the child of the person class
class Student: public Person {
  
  //class attributes
  public:
    int gradyr;
    int gradelvl;
  
  //specify functions as public by using the public keyword before defingthing them
  public: 
    void printProfile(){ //this function will print out all the parent and child attributes
      cout << "Student Name: " << fname << " " << lname << endl;
      cout << "Current Grade: " << gradelvl << endl;
      cout << "Graduation Year: " << gradyr << endl;
      cout << "Email: " << email << endl;

    }
  
}; //end child class definition

int main() { 

  //create a new instance of the child class
  Student student1;

  //set parent attributes
  student1.fname = "Donald";
  student1.lname = "Duck";

  //set child attributes
  student1.gradyr = 2022;
  student1.gradelvl = (student1.gradyr - 2021) + 11; //this calculation is kind of a hack, I'll show you a better way later

  //combine the two
  student1.email = student1.fname+"."+student1.lname+to_string(student1.gradyr)+"@avenues.org";
  //call methods of the child class that accesses the parent attributes
  student1.printProfile();

  return 0;

}